# Generated by Django 4.0.5 on 2022-06-16 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('technologies', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_average', models.FloatField(blank=True, default=0)),
                ('usability_average', models.FloatField(blank=True, default=0)),
                ('content_average', models.FloatField(blank=True, default=0)),
                ('design', models.IntegerField(blank=True, choices=[(1, '1 - poor'), (2, '2 - pathetic'), (3, '3 - very bad'), (4, '4 - bad'), (5, '5 - average'), (6, '6 - good'), (7, '7 - very good'), (8, '8 - perfect'), (9, '9 - exellent'), (10, '10 - genius')], default=0)),
                ('usability', models.IntegerField(blank=True, choices=[(1, '1 - poor'), (2, '2 - pathetic'), (3, '3 - very bad'), (4, '4 - bad'), (5, '5 - average'), (6, '6 - good'), (7, '7 - very good'), (8, '8 - perfect'), (9, '9 - exellent'), (10, '10 - genius')], default=0)),
                ('content', models.IntegerField(blank=True, choices=[(1, '1 - poor'), (2, '2 - pathetic'), (3, '3 - very bad'), (4, '4 - bad'), (5, '5 - average'), (6, '6 - good'), (7, '7 - very good'), (8, '8 - perfect'), (9, '9 - exellent'), (10, '10 - genius')], default=0)),
                ('score', models.FloatField(blank=True, default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(blank='True', default='default.png', upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
