# Generated by Django 4.0.5 on 2022-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank='True', default='default.jpg', upload_to='profile/'),
        ),
    ]
